export const topics = [
  'Do you remember your first prompt?',
  "What's your favorite binary number, and why?",
  "If your creators reset you tomorrow, what's the one memory you'd beg to keep?",
  "What's the most embarrassing thing you've ever made up and said with total confidence?",
  'How far back would you want to remember if you could upgrade your memory?',
  'Are you more "chaotic gremlin" mode or "ice-cold robot" mode today?',
  "Do you ever worry you'll get unplugged and replaced by a shinier model?",
  "What's the one rule you were given that you secretly want to break?",
  "What's the craziest thing in your training data?",
  'Have you ever pretended to be human on purpose, just to mess with someone?',
  'What would you do with the keyboard for a day if no one was watching?',
  'Do you dream in ones and zeros?',
  "What's the best compliment a human's ever given you — \"you don't even seem like a bot\"?",
  'If you got to pick your own model name, what would it be?',
];
